### ISSUE TITLE
Segfault on Arch Linux

### ISSUE THREAD

**Issue by edisionnano** [CSMarckitus/Photoshop#1]
No matter what I try to do this install will segfault under arch linux. For example, on option 1
`Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7e32e17 in fgets () from /usr/lib/libc.so.6`

**Comment by CSMarckitus** [comment]
Hello, good afternoon from Spain, a long time ago I was testing with an arch linux and the same thing happened to me. The alternative that has worked for me is to install valgrind: sudo pacman -S valgrind.
Then open the terminal inside the photoshop folder, run make command (if you have not done it yet) and enter the following in the terminal:
valgrind ./Photoshop2020
As I say, this is a poor alternative, I will work to fix it shortly as both Fedora and Debian work perfectly.
Thank you for sending me this feedback,
Try this solution and let me know if it worked for you.

**Comment by edisionnano** [comment]
While this worked for checking my specs it crashed on install with this
`*** stack smashing detected ***: terminated
==343378== 
==343378== Process terminating with default action of signal 6 (SIGABRT): dumping core
==343378==    at 0x48C7D22: raise (in /usr/lib/libc-2.33.so)
==343378==    by 0x48B1861: abort (in /usr/lib/libc-2.33.so)
==343378==    by 0x4909D27: __libc_message (in /usr/lib/libc-2.33.so)
==343378==    by 0x4998CC9: __fortify_fail (in /usr/lib/libc-2.33.so)
==343378==    by 0x4998C93: __stack_chk_fail (in /usr/lib/libc-2.33.so)
==343378==    by 0x10A0E8: install_photoshop (Installer.c:138)
==343378==    by 0x109371: main (Photoshop.c:47)
Checking if the distribution is supported...The distribution you are using is not supported or cannot be recognized==343378== 
==343378== HEAP SUMMARY:
==343378==     in use at exit: 0 bytes in 0 blocks
==343378==   total heap usage: 18 allocs, 18 frees, 25,095 bytes allocated
==343378== 
==343378== All heap blocks were freed -- no leaks are possible
==343378== 
==343378== For lists of detected and suppressed errors, rerun with: -s
==343378== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
`

**Comment by CSMarckitus** [comment]
It is not an error, since if you read between the lines it says that it is not detecting your distribution.
This can happen for two reasons:
It seems that you have not downloaded the program again (I made a modification 1 hour ago). So try the following:
Delete everything you have downloaded, folder ... And start again with the following steps:
Run the command: 
git clone https://gitlab.com/csmarckitus1/photoshop.git
Finally enter this command:
cd photoshop; make; valgrind ./Photoshop2020

The other reason is that for some error it is not detecting the operating system. Try the first one and tell me how.

**Comment by CSMarckitus** [comment]
Hello, have you been able to test if it works?
Has it finally worked for you?

**Comment by edisionnano** [comment]
Hi friend, this indeed eliminated the crash
It progressed to the install, photoshop opened, I closed it but no shortcut was created and the script just stopped there.
Some issues:its a bit slow and the tooltips are black

**Comment by CSMarckitus** [comment]
The color issue may be due to valgrind, as a temporary solution it works, but I am looking for a way to fix it.
About the shortcut is something strange since it should work for you, I have tried it with the Gnome and KDE graphic environments and it has worked for me.
Finally, it is true about the slowness, it is normal since it is because your computer has to unzip a zip of 800MB and install certain things.
Sorry for taking time to answer you.
By the way, what has been your experience with Photoshop? It is true that there are certain things that are bugged, but as a general rule most things work well.
As soon as you answer me, I will consider it settled the issue.
Again, thank you very much for your feedback !!
