### ISSUE TITLE
Verify PhotoshopCC.tar.xz?

### ISSUE THREAD

**Issue by jonathancross** [CSMarckitus/Photoshop#26]
Has anyone checked [PhotoshopCC.tar.xz](https://gitlab.com/csmarckitus1/photoshop/-/blob/main/files/PhotoshopCC.tar.xz) for malware?

This is the SHA256 hash I got:

    dd0236d2ae85ce895a6159a801db0e0596384f7ecbc7062bdce18f5304f4ba15

Couldn't find any info anywhere on the interwebs...

**Comment by CSMarckitus** [comment]
Hello @jonathancross , 
I understand you, but the problem is that you cant find info on the internet because originally Photoshop isnt a compress file, is simple an installer that directly you download from the Adobe Creative Cloud.

The compress file that I made is directly created from a fresh installation of a cracked Photoshop.

If you or anyone want to be sure that Photoshop doesn't have malware, you can install Photoshop in a Windows or a VM with Windows (even if you have license, you can install the original Photoshop with your license), compress the Photoshop folder and pass it into a GNU/Linux distribution.
(Finally the objective of my script is "This program written in C will help you to automatically install everything you need and configure it so that you can run Photoshop on your Linux without problems.". )

It's also true that as Photoshop is executed with Wine, althought the file had malware, it surely can't execute in Linux because the script for execute the malware probably fails because can't access directly to Linux Kernel. Also because the malware is specialy programmed in a Windows way.
Thanks for share!!
