### ISSUE TITLE
Freezing and Crashing on Ubuntu 22.04

### ISSUE THREAD

**Issue by T3RR5V0N** [CSMarckitus/Photoshop#33]
CPU: AMD Ryzen 5 5600
GPU: AMD Radeon RX 6600 XT

i installed this using the novaspirit tech tutorial video, and whenever i load into the frontpage i just get black, and the app freezes. another user suggested loading into PS with an image, and that works up until i use anything with a dropdown menu, which causes it to instantly CTD.

**Comment by carsonmafa** [comment]
I literally went through the same thing,,, its either its blank or its distorted beyond any functionality,,,, opening it with a picture is the only way ,,, but it isnt as fluid... sometimes it seems like emulating windows and installing the original is better. <unUsable>

**Comment by CSMarckitus** [comment]
Hello @T3RR5V0N and @carsonmafa ,
Yes, you have all the reason and I understand the experience of all the people using it, the script is good, but more work in compatibility is needed for make Photoshop functional on Linux.
I've been thinking for a long time in creating a software similar to Photoshop (something that works similar), in other words, better than the only native photo editor of Linux (Gimp), that in some specific cases works pretty well (because the requirements are very low), but for now I only see as a long term project, I need to grew more for make a better software because now I'm 17 years old and I want/need to upgrade my skills a 1000x (at least) for produce a better software and a enjoyable user experience.
For now the solution I recommend is that if you don't need all the advanced functionalities that Photoshop give, you can use https://www.photopea.com/, but be careful with sensitive files (because like everything, is a web service).
