### ISSUE TITLE
error: sorry something went wrong during download photoshopCC-V19.1.6-2018x64.tgz

### ISSUE THREAD

**Issue by Ahmedk-n** [CSMarckitus/Photoshop#35]
Whenever I try to install it it gives me this weird error
using curl to download photoshopCC-V19.1.6-2018x64.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   157  100   157    0     0     14      0  0:00:11  0:00:11 --:--:--    41
md5 is not match
downloading photoshopCC-V19.1.6-2018x64.tgz ...
using curl to download photoshopCC-V19.1.6-2018x64.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   157  100   157    0     0     14      0  0:00:11  0:00:10  0:00:01    50
md5 is not match
downloading photoshopCC-V19.1.6-2018x64.tgz ...
using curl to download photoshopCC-V19.1.6-2018x64.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   157  100   157    0     0     14      0  0:00:11  0:00:10  0:00:01    38
error: sorry something went wrong during download photoshopCC-V19.1.6-2018x64.tgz`
`

**Comment by CSMarckitus** [comment]
Hello @Ahmedk-n ,
This error is because you are using the curl tool to download only the file that contain the Photoshop files.
Instead, read the docs for know how to install it (because starts with git clone https://gitlab.com/csmarckitus1/photoshop.git ...) or if you want you can watch the video recommended in the readme for see visually how to install it.
Thanks for your feedback and I want to read your experience when finish the installation.
