### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by AireagoirSteam** [CSMarckitus/Photoshop#38]
could you add an install from the multilingual version of photoshop or ad english gb files please?

**Comment by CSMarckitus** [comment]
Hello @AireagoirSteam ,
Yeah, I know that some people want the English version, I try to do it during this week.
Thanks for your feedback!

**Comment by CSMarckitus** [comment]
Hello again @AireagoirSteam ,
Good news, because finally today in a couple of hours I'm will update the Photoshop with English language and with a updated 21.2.4 version!! 
Now the people can choose in the installation the language they want (English or Spanish).
As all in life, there are only one disadvantage in terms of choosing the language, and that is that now maybe the download (git clone) of Photoshop it will take a little longer.
**For the people that want to know what I optimize:**
I desactivated the use of GPU processor and optimized the RAM usage.
If anyone want to use the GPU processor it can be enabled from the Settings window but for a lot of people I think that it is the cause of the most crashes.
![image](https://user-images.githubusercontent.com/88045486/190923949-195a173d-6573-434a-8f09-6fd0d445ef5c.png)

**Comment by CSMarckitus** [comment]
Hello @AireagoirSteam ,
Now the Photoshop 21.2.4 version is finally here!!
You can try the new version with the same steps. During the installation you will see the choice of your desired language.
So as always, I love to read your feedbacks for improve all!

**Comment by em1xq** [comment]
no options for language during installation unfortunatel, even in ps settings

**Comment by CSMarckitus** [comment]
Hello @em1xq ,
Yes, now I'm looking the repo but the changes are not published, tonight I'll figure it out.

**Comment by CSMarckitus** [comment]
Hello @em1xq ,
Finally I push all the changes, so now all of you can download the 21.2.4 version.
I was having trouble uploading the new files on Gitlab and Cloudflare.
I hope everything goes perfectly, any problem I'll be here.
