### ISSUE TITLE
No US Language

### ISSUE THREAD

**Issue by aIacoella** [CSMarckitus/Photoshop#42]
After installing the software with "International" language support no languages other than spanish are available.
Also the en_us language package is not available in the repo anymore.

How can i switch language to english?

**Comment by CSMarckitus** [comment]
Hello @aIacoella ,
Thanks for share your feedback to others, I think that's my problem because when the program asks you for what language you want to choose you need to write (choose) literally: english or spanish.
Maybe I need to be more clear, because when I write what language you want to choose English (International) or Spanish I'm referring to the variant of English.
Is that the solution to your problem or do you write english but it still doesn't work?

**Comment by Atef98** [comment]
Yes, the same thing happened to me I write "English" but it doesn't work, so what should I do?

**Comment by CSMarckitus** [comment]
Hello @Atef98 ,
Yes, you have all the reason, before that issue the script only detects the writing of: "english", all in lowercase. Now I fix it, so if you download again the script it detects "English" or "english". But if you want to save time avoiding to download all again, write simply: "english". If you don't write it correctly, by default the Spanish language is installed.
Thanks for your feedback!

**Comment by Atef98** [comment]
Thanks, @CSMarckitus 
 I preferred to do it manually,
 so I extract photoshop/files/PhotoshopCCEnglish.tar.xz and in the Locals folder I copy the en_GB  package.
 paste it in PhotoshopCC/Photoshop-CC/Locales/, and everything work fine now.

**Comment by CSMarckitus** [comment]
Hello @Atef98 ,
Yessss, also another totally valid solution. Ultimately I wanted to propose the most easy and valid solution for people, but if anyone want to do it in another way, is also correct. And if the people share his improvements to all of us, I will be very grateful.

Thanks for share your method with us!
