### ISSUE TITLE
Question: origin of photoshop software it self, use of my own license key

### ISSUE THREAD

**Issue by Sjakub5** [CSMarckitus/Photoshop#47]
Hi,

when you said it´s free and it won´t require license key, does it mean, that photoshop software is cracked? Where did you get the software for this installer? Can I use my own license key? I just want use legit software.

Thanks and best regards

**Comment by CSMarckitus** [comment]
Hello @Sjakub5 ,
That's a good question. Yes, with free I mean that I crack the software.

My point of view about this is that Photoshop should be like Davinci Resolve. Davinci Resolve is one of the best video editor programs and it is compatible with Windows, Linux and MacOS. 
As a developer I can understand that it may bother share the final software without pay for it, but in the other hand I think that they have a very good software and a lot of people want to use it (and we would be willing to pay), and for a company like Adobe it can't cost a lot make his program compatible with Linux (because mostly of it is writted in C++).

For this reason and for help to people that is thinking to make the jump from Win to "Linux" world, I make the installer super easy. 

**The problem is that if you want to install the official software, the installer doesn't work with this script and also for Wine. For this reason, if you want to install it officialy, there are one workaround:**
- Create a Virtual Machine with Wndows 10 and download and install the official Photoshop with your original key.
- When Photoshop is installed, go to Program Files, Adobe and move the Photoshop folder, that it contains all the files of the SW, from the VM to the path where you download this script, specifically in the files folder.
- Compress the folder using the .tar.xz and with the same name of the version that you want, in other words, if you want the English version, name the compress file to PhotoshopCCEnglish.tar.xz.
- Finally run this script.
**NOTE:** I don't try the Photoshop 2022 versions, but I think that it don't work with this script (truly with Wine), so you will have to search how to download the Photoshop v21.

Thanks a lot for your question, I think the same as you, I appreciate the official sw and license, but also I wanted to offer something easy to people.
