### ISSUE TITLE
Can't open user.reg file / Install won't complete

### ISSUE THREAD

**Issue by eli876** [CSMarckitus/Photoshop#8]
Good day,
I can't seem to get the installer to work on the last step. After changing my windows version to Windows 10, I get "Can't open user.reg file.Click on Install to everything it asks for.Setting dark..." and it exits. I never get the prompt to install photoshop for all users or just myself. I'm on debian 11.

Best,

Eli

**Comment by CSMarckitus** [comment]
Hello @eli876 sorry for slow respond.
The problem is that it seems that your computer does not want to allocate more memory to create the file, do you have enough RAM and disk?

Anyway, what I would do is try to install valgrind:
sudo apt install valgrind
And run the file as follows:
sudo valgrind ./Photoshop
Try it and tell me if it worked for you. If you get any error copy it and paste it here please.
Thanks for your feedback!

**Comment by CSMarckitus** [comment]
Hello @eli876 ,
Finally, has it worked for you?

**Comment by eli876** [comment]
Hi,
Thanks for the detailed response. My system has 32gb of ram and more 
than 100 gb of free space, so I didn't consider valgrind.
I will try your suggestion today and let you know.

Best,

**Comment by eli876** [comment]
Hi,
I got it to work with valgrind. Thanks again for your incredible work 
on this!
